# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
gfcli:
  # 工具编译配置
  build:
    name: "shop"
    arch: "amd64"
    system: "linux,darwin,windows"
    mod: ""
    cgo: 0

  # dao生成
  gen:
    dao:
      - link: "mysql:homestead:secret@tcp(192.168.10.10:3306)/gfDemo"
        #tables: "user"
        removePrefix: "gf_"
        descriptionTag: true
        noModelComment: true
